package com.caiocesarmods.caioclimates.Climate;

public enum ClimateType {
    MEDITERRANEAN_HOT, MARITIME_MEDITERRANEAN, TROPICAL_SAVANNA, HUMID_SUBTROPICAL, MARITIME_TEMPERATE, MARITIME_HUMID_SUBTROPICAL,
    HEMIBOREAL_TEMPERATE, MARITIME_TROPICAL,
    TROPICAL_RAINFOREST, TROPICAL_RAINFOREST_EDGE, RAINFOREST_HUMID_SUBTROPICAL, TROPICAL_XERIC_STEEPE,
    TUNDRA, HUMID_TEMPERATE,
    MEDITERRANEAN_MARITIME_TEMPERATE, XERIC_TEMPERATE_CONTINENTAL, TAIGA, SNOWY_TAIGA, ICE_CAP, TROPICAL_DESERT, SUBTROPICAL_DESERT,
    MARITIME_SUBTROPICAL_DESERT
}
